### ISSUE TITLE
Some thing goes wrong.

### ISSUE THREAD

**Issue by Yuhuoo** [ingra14m/floater-free-gaussian-splatting#1]
When ran the render.py to get a video, I have got this error.

Traceback (most recent call last):
  File "render.py", line 264, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test, args.render_video)
  File "render.py", line 245, in render_sets
    render_video(dataset.model_path, scene.loaded_iter, scene.getTrainCameras(), gaussians, pipeline, background)
TypeError: 'bool' object is not callable

**Comment by ingra14m** [comment]
Hi, I have fixed the parameter bug in the latest commit. Thanks for pointing that out.

**Comment by dhanyacp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
TimiBolu, @yashwantx, @bitbuyandrew, @oiserworld, @mdias, @romanshilpakar, @oohwahaha, @Stijnnys, @Manifest1, @CM-Talha, @jt851113, @christiangebel, @paypur, @xdefrag, @shine2024, @thisislexar, @zanyfly, @PeterChen1997, @trimclain, @teslaxi, @kashyapabhinav1906, @Demuirgos, @Srujan-D, @JohnCoconut, @Emeka-12, @zoubingwu, @vitye, @D3VinEd, @laskaridis, @super117893344p, @LeeReindeer, @essldd, @vieri03, @robbidb, @LewisMojica, @urkin-dev, @DreamShaded, @opaulooo, @BenCamps, @Rongnisun, @MnAppsNet, @jeremyallencpa, @meta-atom, @harrisrobin, @BlazeWits, @akshay-bhimani-pedalsup, @n1rupam, @rafatackla, @nachoverdon, @drizzyrdrgz-exe
